<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Monii.Infrastructure/Monii.Infrastructure.csproj" /></ItemGroup>
  <ItemGroup><None Include="../../updates/stable.json" Link="stable.json" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
